### ISSUE TITLE
ComposeEngine

### ISSUE THREAD

**Issue by RobiNN1** [php-fusion/PHP-Fusion#1054]
F:\xampp\htdocs\PHP-Fusion\includes\classes\PHPFusion\Page\Composer\Network\ComposeEngine.php
/administration/custom_pages.php?aid=259c2fb1c8e36f0c&section=compose_frm&action=edit&cpid=1&composer_tab=pg_composer&compose=add_row
Undefined index: page_grid_container
Line: 290

**Comment by meangczac** [comment]
The setup has been updated:

"custom_pages_grid" => " (
        page_id MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
        page_grid_id MEDIUMINT(9) UNSIGNED  NOT NULL AUTO_INCREMENT,
        page_grid_container TINYINT(1) NOT NULL DEFAULT '0',
        page_grid_column_count TINYINT(1) NOT NULL DEFAULT '0',
        page_grid_html_id VARCHAR(50) NOT NULL DEFAULT '',
        page_grid_class VARCHAR(100) NOT NULL DEFAULT '',
        page_grid_order TINYINT(5) NOT NULL DEFAULT '0',
        PRIMARY KEY (page_grid_id),
        KEY page_id (page_id)
        ) ENGINE=MyISAM DEFAULT CHARSET=UTF8 COLLATE=utf8_unicode_ci",

**Comment by RobiNN1** [comment]
After reinstall not  working

**Comment by meangczac** [comment]
What error remains?
